FROM node:10-alpine
MAINTAINER V-Wong
LABEL repo=https://github.com/V-Wong/backend-template

RUN mkdir -p /usr/app
WORKDIR /usr/app
COPY ./backend/package.json ./backend/tsconfig.json ./
COPY ./backend/src ./src
COPY ./types /usr/types
RUN npm install
RUN npm run build

CMD ["npm", "run", "dev"]