FROM node:10-alpine
MAINTAINER V-Wong
LABEL repo=https://github.com/V-Wong/backend-template

WORKDIR /usr/src
COPY ./types ./types
COPY ./backend/.env ./

WORKDIR app
COPY ./backend/package.json ./backend/tsconfig.json ./
COPY ./backend/src ./src
RUN npm install
RUN npm run build
COPY ./backend/.env ./

WORKDIR /usr/src
CMD ["node", "app/dist/app/src/app.js"]